config/routes.rb
Rails.application.routes.draw do
  match 'startup/sign_up_action' => 'startup#events', via: [:get, :post]
  resources :widgets
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'startup#index'
  get '/startup/contacts', to: 'startup#contacts'
  get 'startup/index', to: 'startup#index'
  get 'startup/events', to: 'startup#events'
  get 'startup/profile', to: 'startup#profile'
  post 'startup/events', to: 'startup#sign_up_action'
  post '/startup/events', to: 'startup#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base #seperate from sti libary
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord 
end

app/models/user.rb
class User < ApplicationRecord
  #model for user in database
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #Allows for the adding of stars to the user profile
  def addStars(num)
    self.stars += num
  end
  
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

#safety net

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

  def sign_up_params #set up the varables need to sign into or create a profile
    params.require(:user).permit(:username, :phone, :email, :password, :password_confirmation)
  end

  def account_update_params #set up the varables for changing user data
    params.require(:user).permit(:username, :phone, :email, :password, :password_confirmation, :current_password)
  end
end

class CheckControl < ActiveRecord::Base
  #was added but could not find a way to make it work in new.html in registation folder of models
  validates_format_of :phone, :with => /[0-9]{3}-[0-9]{3}-[0-9]{4}/
  
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index #allows the main page to display events from database in the widget
    @events = Event.all
  end
  
  def events #allows the events to display events from database and allow users to sign up for events
    @events = Event.all
  end
  
  #def create
   # render text: params.inspect
    #@events = Event.new
    #@place = params[:place]
    #@desc = params[:desc]
    #@time = params[:time]
    #@day = params[:day]
    #@stars = params[:stars]
    
  #end
  
  def contacts #allows the contacts page to display all the members and their contact info
    @users = User.all
    @users.each do |user|
      puts user.username
    end
  end
  
  def admins #allows admins to have access to restricted commands
    @admins = User.all
    @admins.each do |admin|
      puts user.username
    end
  end
  
  #supposed to take data from events signup and apply to user profile 
  def sign_up_action
    current_user.stars += num
    current_user.save!
    print "hello"
  end
  
  #parce the data from events signup
  def parse_comments
    comments_from_new_event = params['myforum']['place']['what']['time']['day']['stars']
  end
  
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  #widget varables
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index #creates widgets on the main page
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show #for future use
  end

  # GET /widgets/new
  def new #widget creation on page
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit #for future use
  end

  # POST /widgets
  # POST /widgets.json
  def create #constructer
    @widget = Widget.new(widget_params)

    respond_to do |format| #check if creation is done correctly 
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format| #check if update was done correctly is done correctly 
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format| #delete the widgets
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper #not used
end

app/helpers/startup_helper.rb
module StartupHelper #not used
end

app/helpers/widgets_helper.rb
module WidgetsHelper #not used
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <%#= page header %>
    <title>Her Stars</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles', 'data-turbolinks-track': 'reload', :media => 'all' %>
  </head>

  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=The+Girl+Next+Door" />
  <body>
    <h1 class="header">
      <a href="/startup/index">
      <div class="upper-header">Her Stars</div>
      <div class="sub-header">A Her Campus Extension</div>
      </a>
    </h1>
    <!-- Navigation -->
    <div class = "dropdown">
      <div class="w3-dropdown-click">
        <img src="https://photos-6.dropbox.com/t/2/AADjWG9ZJENl2tyA3cSCO2dBP8oUKDeWHrPU0p5Ppe6MHg/12/81332145/png/32x32/1/_/1/2/menuButton.png/EJLApD8YEiACKAI/u9KPEBekQVJx8W9-Wj6vaFZntE02L0oLx6vmHL8h__k?preserve_transparency=1&size=2048x1536&size_mode=3" class="w3-button hamburgerIcon" onclick="myFunction()">
        <div id="demo" class="w3-dropdown-content w3-bar-block ">
          <a href="/startup/index" class="w3-bar-item w3-button">Home</a>
          <a href="/startup/contacts" class="w3-bar-item w3-button">Contacts</a>
          <a href="/startup/events" class="w3-bar-item w3-button">Events</a>
          <%- if user_signed_in? %>
          <a href="/startup/profile" class="w3-bar-item w3-button">Profile</a>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
          <a href="/users/sign_up" class="w3-bar-item w3-button">Users</a>
        <% end %>
        </div>
      </div>
    </div>
    <nav id="mainNav">
      <div class="topnav"> <%#= page links on each page %>
        <a href="/startup/index">Home</a>
        <a href="/startup/contacts">Contacts</a>
        <a href="/startup/events">Events</a>
        <% if notice %><div class="allert alert-info"><%= notice %></div><% end %>
        <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
        <%- if user_signed_in? %>
          <a href="/startup/profile">Profile</a>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
          <a href="/users/sign_up">Users</a>
        <% end %>
        </div>
    </nav>
<%=yield%>

  <style> <%#= put footer at bottom of screen%>
  .footer {
    position: fixed;
    bottom: 0;
    left: 0;
    font-size: medium;
    width:100%;
    text-align: center;
    color: white;
  }
  </style>
    <div class="footer"> <%#= the text of the footer%>
        <p>Copyright &copy; Her Stars 2018</p>
    </div>
    <script>
function myFunction() { <%#= not used presently %>
    var x = document.getElementById("demo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else { 
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>
  </body>
</html>

app/views/startup/contacts.html.erb
<section> <%#= the contacts page %> 
    <div class="intro-title">Contacts</div>
    <table id = contactlist class="tableSection">
      <thead>
        
        <tr> <%#= titles of the columns of contact information: name, phone number, Email, and if admin %>
          <th><span class="text">Name</span>
    
          </th>
          <th><span class="text">Number</span>
    
          </th>
          <th><span class="text">Email</span>
    
          </th>
          </th>
           <%#<th><span class="text">Admin?</span>%>
          
          </th>
        </tr>
      </thead>

      <tbody> <%#= for each user places their information in the proper column %>
        <% @users.each do |user|%>
        <tr>
          <%# This is where each function from the user in the db will go %>
          <td><%= user.username %></td>
          <td>#: <%= user.phone%></td>
          <%# I didn't find anything in the db about storing a user's phone number %>
          <td><%= user.email%></td>
          <%#<td><%= user.admin%><%#</td>%>
        </tr>
        <% end %>
      </tbody>
      

      
  
  
  
<%
=begin %>
      <tbody> example data
        <tr>
          <td>Vera Taylor</td>
          <td>555-555-5555</td>
          <td>reddit-is-life@tamu.edu</td>
        </tr>
        <tr>
          <td>Katie Caldwell</td>
          <td>555-555-5555</td>
          <td>frogs@tamu.edu</td>
        </tr>
        <tr>
          <td>Pauline Norman</td>
          <td>555-555-5555</td>
          <td>tamu-loves25x25@tamu.edu</td>
        </tr>
        <tr>
          <td>Ruby Morgan</td>
          <td>555-555-5555</td>
          <td>hewhomshallnotbenamed@tamu.edu</td>
        </tr>
        <tr>
          <td>Joyce Heinrich</td>
          <td>555-555-5555</td>
          <td>darklordsauron@tamu.edu</td>
        </tr>
        <tr>
          <td>Pearl Vernon</td>
          <td>555-555-5555</td>
          <td>he-who-sleeps@tamu.edu</td>
        </tr>
        <tr>
          <td>Amanda Dexter</td>
          <td>555-555-5555</td>
          <td>praise-cthulhu@tamu.edu</td>
        </tr>
        <tr>
          <td>Betty Reese</td>
          <td>555-555-5555</td>
          <td>keklord@tamu.edu</td>
        </tr>
        <tr>
          <td>Evelyn Tufts</td>
          <td>555-555-5555</td>
          <td>stuff@tamu.edu</td>
        </tr>
        <tr>
          <td>Cora Sterling</td>
          <td>555-555-5555</td>
          <td>ilove-aws@tamu.edu</td>
        </tr>
        <tr>
          <td>Eleanor Parker</td>
          <td>555-555-5555</td>
          <td>narsil@tamu.edu</td>
        </tr>
        <tr>
          <td>Louise Lane</td>
          <td>555-555-5555</td>
          <td>notsuperman@tamu.edu</td>
        </tr>
        <tr>
          <td>Louise Zimmer</td>
          <td>555-555-5555</td>
          <td>cloud9or-so@tamu.edu</td>
        </tr>
        <tr>
          <td>Winifred Durwood</td>
          <td>555-555-5555</td>
          <td>0outof100@tamu.edu</td>
        </tr>
        <tr>
          <td>Donna Rice</td>
          <td>555-555-5555</td>
          <td>ea-lovesmoney@tamu.edu</td>
        </tr>
      </tbody>
      
      <%
=end %>


    </table>
</section>

app/views/startup/events.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<%#= pulls event from and adds events to database table%>


<section>
    <%#=<div class="intro-title">Events</div>%>
    <div class="blank space">.</div>
    <div class="intro-subtitle">Sign Up For Events Here</div> <%#= instructions for page usage %>
    <!-- Trigger/Open The Modal -->
    <button id="myBtn">New Event</button>  <%#= allow the adding of a new event to database table %>
    <!-- The Modal -->
    <div id="myModal" class="modal">
      <!-- Modal content -->
      <div class="modal-content" style="color:black">
        <span class="close">&times;</span>
        
          <!--Should send all data entry to startup_controller.rb-->
        Place<br>
        <input type="text">
        <br>
        Type of Event<br>
        <input type="text">
        <br>
        Time<br>
        <input type="text">
        <br>
        Day<br>
        <input type="text">
        <br>
        Stars<br>
        <input type="text"><br><br>
        <input id="sub" type="submit" value="Submit">
        <br><br>
      </div>
    
    </div>
    <script>
      var modal = document.getElementById('myModal');
      var btn = document.getElementById("myBtn");
      var span = document.getElementsByClassName("close")[0];
      var sub = document.getElementById("sub");
      btn.onclick = function() {
          modal.style.display = "block";
      }
      span.onclick = function() {
          modal.style.display = "none";
      }
      sub.onclick = function() {
          modal.style.display = "none";
      }
      window.onclick = function(event) {
          if (event.target == modal) {
              modal.style.display = "none";
          }
      }
      // function updateItem(place, type, time, day, stars) {
      //   var e = document.getElementById(item);
      //   var val = e.options[e.selectedIndex].value; 
      //   new Ajax.Request('/startup/update_event_table', { 
      //                 method: 'post',
      //                 parameters: { selected_id: item, u_id: userID, job_id: jobID }
      //               });
    </script>
    <table class="tableSection"> 
      <thead> <%#= column headers for event information%>
        <tr>
          <th><span class="text">Where</span>
    
          </th>
          <th><span class="text">Description</span>
    
          </th>
          <th><span class="text">When</span>
    
          </th>
          <th><span class="text">Date</span>
    
          </th>
          <th><span class="text">Stars</span>
    
          </th>
          <th><span class="text">Sign Up!</span>
    
          </th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event|%> <%#= for each event display name, description, time, day, and stars %>
        <tr>
          <%# This is where each function from the user in the db will go %>
          <td><%= event.name %></td>
          <td><%= event.desc%></td>
          <td><%= event.time %></td>
          <td><%= event.day%></td>
          <td><%= event.stars%></td>
          <td><%= link_to "Sign Up!", { :controller => "startup", :method => :put, :action => "sign_up_action" } %></td>
        </tr> <%#= when sign up is pressed the stars and event discription and date are sent to the user %>
        <% end %>
         </tbody>
      
      

      <%
=begin %> //example data, outdated
      
      <tbody>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>Kick off Party!</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 1</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>First official meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 2</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 2</pre>
          </td>
        </tr>
         <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 1</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 5</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>Midterm Potluck and De-Stress</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 3</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 3</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 2</pre>
          </td>
        </tr>
        <tr>
          <td>Wolf Pen Creek Park
            <pre>General Meeting</pre>
          </td>
          <td>17:00<pre>Thursday</pre></td>
          <td><a href="https://tinyurl.com/j8jxawj">Sign Up!</a>
            <pre>Stars: 3</pre>
          </td>
        </tr>
      </tbody>
<%
=end %>
      
      
      
    </table>


</section>

app/views/startup/index.html.erb
<section>
  <div class="intro-text-home"> <%#= welcome message and reason for website %>
    <p>Welcome to Her Stars! 
                          This is where you can find upcoming events, find
                          other members, and track your attendance.</p>
  </div>
  <div class="widget"> <%#= create widget that hold the first three events %>
    <p class="widget-sign-up-text">Sign Up!</p>
    <p class="widget-sign-up-events">events</p>
    
    <tbody>
          <% @events.first(3).each do |event|%> <%#= for the first three events %>
          <tr> <%#= display discription, day of event, time, and star %>
            <%# This is where each function from the user in the db will go %>
            <td> 
              <%= event.name %>
              <pre><%= event.day%></pre>
              <td>
               <%= event.time %>
              </td>
              <pre><%= event.stars%> stars</pre>
              <pre><a href="/startup/events">Sign Up!</a></pre> <%#= when pressed go to events page %>
            </td>
             <p class="divider">-------------------</p>
            <td>
              
            </td>
          </tr>
          <% end %>
      </tbody>
    
  </div>
</section>

app/views/startup/profile.html.erb
<section>
    
    <div class="intro-title">Hello, <%= current_user.username %></div> <%#= displays username %>
    <div class="intro-subtitle">Total Stars: <%= current_user.stars %></div> <%#= total stars earned by user %>
    <% if current_user.admin == false %>
      <table class="tableSection">
        <thead>
          <tr> <%#= column headers for event description, date and stars obtained %>
            <th><span class="text">event Description</span>
      
            </th>
            <th><span class="text">Date</span>
      
            </th>
            <th><span class="text">Stars Obtained</span>
            </th>
          </tr>
        </thead>
         
        <td>Wolfpen Creek</td>
        <td>11/13/2018</td>
        <td>0</td>
      </table>
      
      <!-- need to change method to post to protect key info -->
      <form method="get">  <%#= not currently implemented %>
        Are you an Admin? <br>
        Input Admin key here : <br>
        <input type="text" name = "adminkey"><br>
        <input type="submit" value="Submit"><br>
      </form>
    <% else %>
      <!-- admin queue goes here -->
    <% end %>

</section>

app/views/widgets/_form.html.erb
<%= form_with(model: widget, local: true) do |form| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :widget_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>